services:
  api:
    depends_on:
      db: 
        condition: service_healthy
    container_name: flashlearn_api
    env_file:
      - .env
    build: ./api
    ports:
      - "5001:5001"
    volumes:
      - ./api:/app
      - /app/node_modules
  db:
    image: mysql
    container_name: flashlearn_db
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-pflashlearn2023"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - 3306
volumes:
  mysql: