services:
  api:
    restart: always
    depends_on:
      redis: 
        condition: service_healthy
    container_name: flashlearn-api
    image: 973495919933.dkr.ecr.ap-southeast-1.amazonaws.com/flashlearn-api
    env_file:
      - production.env
    build: ./api/
    command: ["npm", "run", "prod"]
  redis:
    restart: always
    image: redis:latest
    container_name: flashlearn-redis
    healthcheck:
      test: ["CMD", "redis-cli" ,"ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - redis:/var/lib/redis
    ports:
      - 6379:6379
  nginx:
    restart: always
    depends_on:
      - api
    image: 973495919933.dkr.ecr.ap-southeast-1.amazonaws.com/flashlearn-nginx
    container_name: flashlearn-nginx
    build: ./nginx/
    ports:
      - 80:80
    
volumes:
  mysql:
  redis: