services:
  api:
    restart: always
    depends_on:
      db: 
        condition: service_healthy
    container_name: flashlearn-api
    image: flashlearn-api:latest
    env_file:
      - .env
    build: ./api/
  db:
    restart: always
    image: mysql
    container_name: flashlearn-db
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-pflashlearn2023"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
  redis:
    restart: always
    image: redis:latest
    container_name: flashlearn-redis
    healthcheck:
      test: ["CMD", "redis-cli" ,"ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - redis:/var/lib/redis
    ports:
      - 6379:6379
  proxy:
    restart: always
    depends_on:
      - api
    image: flashlearn-reverse-proxy:latest
    container_name: flashlearn-reverse-proxy
    build: ./nginx/
    ports:
      - 80:80
    
volumes:
  mysql: