name: Deploy FlashLearn

# run workflow on every push
on:
  push:
    branches:
      ["main"]
jobs:
  deploy:
    # run workflow on ubuntu with permissions
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-role
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Build, tag, and push flashlearn-api image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: flashlearn-api
          IMAGE_TAG: latest
        run: |
          # build image
          docker buildx build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --platform=linux/amd64 ./api
          # push docker image
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Build, tag, and push flashlearn-nginx image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: flashlearn-nginx
          IMAGE_TAG: latest
        run: |
          # build image
          docker buildx build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --platform=linux/amd64 ./nginx_prod
          # push docker image
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        with:
          host: ${{ secrets.FLASHLEARN_SSH_HOST }}
          username: ${{ secrets.FLASHLEARN_SSH_USER }}
          key: ${{ secrets.FLASHLEARN_SSH_KEY }}
          port: 22
          envs: AWS_REGION, AWS_ACCOUNT_ID
          script: |
            cd ./app/flashlearn-api
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
            docker compose -f production.yaml down
            docker compose -f production.yaml rm -sf
            docker image prune -af
            docker compose -f production.yaml pull
            docker compose -f production.yaml up -d
            
